#! /bin/sh

sxhkd &

~/.config/polybar/launch.sh &

bspc monitor -d ૧ ૨ ૩ ૪ ૫ ૬ ૭ ૮ ૯ ૧૦ 

bspc config top_padding 0

bspc config border_width 2
bspc config window_gap 10

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Zathura state=tiled
