# make sure $userclientrc is set to $HOME/.config/X11/xinitrc in /usr/bin/startx script

#export _JAVA_AWT_WM_NONREPARENTING=1 &

xmodmap ~/.config/X11/Xmodmap &

xrdb ~/.config/X11/Xresources-moonfly &

set-wallpaper ~/Pictures/wallpapers/ &

dunst &

redshift -P -O 2700 &

picom &

xset r rate 300 50 &

unclutter --timeout 3 &

dwmblocks &

while type dwm >/dev/null ; do dwm && continue || break ; done
