# make sure $userclientrc is set to $HOME/.config/X11/xinitrc in /usr/bin/startx script

#export _JAVA_AWT_WM_NONREPARENTING=1 &

xmodmap ~/.config/X11/Xmodmap &

xset r rate 300 50 &

killall mpd ; mpd &

killall xbanish ; xbanish &

killall flameshot ; flameshot &

killall dwmblocks ; dwmblocks &

(dmenu-change-font "Fantasque Sans Mono" ; dmenu-change-mode gruvbox_dark) &

set-wallpaper ~/Pictures/wallpapers/ &

redshift -P -O 2700 &

picom -b

dwm
